"""tags

Revision ID: 2dc6f65a957e
Revises: 63e41b62f0f7
Create Date: 2023-04-14 13:56:21.462489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc6f65a957e'
down_revision = '63e41b62f0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('Math', sa.Integer(), nullable=True),
    sa.Column('Science', sa.Integer(), nullable=True),
    sa.Column('History', sa.Integer(), nullable=True),
    sa.Column('English', sa.Integer(), nullable=True),
    sa.Column('Politics', sa.Integer(), nullable=True),
    sa.Column('Language', sa.Integer(), nullable=True),
    sa.Column('Arts', sa.Integer(), nullable=True),
    sa.Column('Packer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    # ### end Alembic commands ###
