"""users table

Revision ID: 953490b5ae1b
Revises: 5db08cf4f46a
Create Date: 2023-03-06 08:38:18.372461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953490b5ae1b'
down_revision = '5db08cf4f46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
